---

# ImageStreams
hello_world_is_image_latest_tag: "2.0"
hello_world_is_image_tag: "1.0"
hello_world_is_image_name: "gcr.io/google-samples/hello-app:1.0"
# DeploymentConfigs
hello_world_dc_image: "{{ meta.name }}-hello-world:latest"
hello_world_dc_replicas: 2
hello_world_dc_resources_requests_cpu: "50m"
hello_world_dc_resources_requests_memory: "32Mi"
hello_world_dc_resources_limits_cpu: "100m"
hello_world_dc_resources_limits_memory: "64Mi"
# Routes
hello_world_route_hosts: "hello-world.example.net"
