---

- name: Manage hello-world ImageStream
  k8s:
    definition: "{{ lookup('template', 'hello-world-imagestream.yml.j2') }}"

- name: Get details of deployed hello-world DeploymentConfig if exists
  k8s_facts:
    api_version: v1
    kind: DeploymentConfig
    namespace: "{{ meta.namespace }}"
    name: "{{ meta.name }}-hello-world"
  register: hello_world_dc_register

- name: Set real ImageStream image with internal registry hash of hello-world DeploymentConfig if exists
  set_fact:
    hello_world_dc_image: "{{ hello_world_dc_register.resources[0].spec.template.spec.containers[0].image }}"
  when: hello_world_dc_register.resources[0] is defined

- name: Manage hello-world DeploymentConfig
  k8s:
    definition: "{{ lookup('template', 'hello-world-deploymentconfig.yml.j2') }}"

- name: Manage hello-world Service
  k8s:
    definition: "{{ lookup('template', 'hello-world-service.yml.j2') }}"

- name: Manage hello-world Route
  k8s:
    definition: "{{ lookup('template', 'hello-world-route.yml.j2') }}"
