apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world-operator
  labels:
    name: hello-world-operator
    monitoring: 'enabled'
spec:
  selector:
    matchLabels:
      name: hello-world-operator
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
